#! /bin/sh

export LIBGL_DRIVERS_PATH=${SNAP}/graphics/dri
export __EGL_VENDOR_LIBRARY_DIRS=${SNAP}/graphics/glvnd/egl_vendor.d

if [ ! -e $XDG_RUNTIME_DIR/pulse ]; then
    ln -sf ../pulse $XDG_RUNTIME_DIR/pulse
fi

exec "$SNAP/pvms"
