name: pocketvms
version: "1.0"
summary: A convergent QEMU frontend for desktop and mobile
description: |
  Pocket VMs is a QEMU frontend for Ubuntu Touch & Ubuntu Desktop

  Features:
  - A custom build of QEMU
  - A native & convergent GUI
  - Emulation (x86_64 on aarch64)
  - Virtualization (aarch64 on aarch64) using KVM
  - File sharing support
  - Easy to use machine management
  - Tight Ubuntu Touch integration

grade: stable
confinement: strict
base: core24

platforms:
  amd64:
    build-on: amd64
  arm64:
    build-on: arm64

plugs:
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: hybris-2404
  lomiri-ui-toolkit:
    interface: content
    target: $SNAP/lomiri-ui-toolkit
    default-provider: lomiri-ui-toolkit-core24

layout:
  /usr/share/libdrm:  # Needed by mesa-core20 on AMD GPUs
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:  # Used by mesa-core20 for app specific workarounds
    bind: $SNAP/graphics/drirc.d
  /usr/share/X11/xkb:
    bind: $SNAP/usr/share/X11/xkb
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /etc/fonts:
    bind: $SNAP/etc/fonts

apps:
  pocketvms:
    environment:
      PATH: ${SNAP}/bin:${SNAP}/usr/bin:${SNAP}/command-chain:$PATH
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/lomiri-launch
    command: pvms
    plugs:
      - audio-playback
      - audio-record
      - kvm
      - home
      - opengl
      - raw-usb
      - removable-media
      - screen-inhibit-control
      - network
      - network-bind
      - network-control
      - unity7
      #- unity8
      - x11
      - wayland
      - desktop
      - maliit
      #- content-hub

parts:
  pvms:
    source: .
    plugin: cmake
    build-snaps:
      - lomiri-ui-toolkit-core24
    override-build: |
      cd $CRAFT_PART_SRC
      export CMAKE_MODULE_PATH=/snap/lomiri-ui-toolkit-core24/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake
      git config --global --add safe.directory $CRAFT_PART_SRC/3rdparty/qemu
      ./build.sh -c
    override-prime: |
      craftctl default
      cp -a /snap/lomiri-ui-toolkit-core24/current/command-chain/lomiri-launch ${CRAFT_PRIME}/bin/lomiri-launch
    build-packages:
      - autoconf
      - automake
      - bison
      - ccache
      - flex
      - gettext
      - gtk-doc-tools
      - libtool
      - libaio-dev
      - libbluetooth-dev
      - libbrlapi-dev
      - libbz2-dev
      - libcap-dev
      - libcap-ng-dev
      - libcurl4-gnutls-dev
      - libdrm-dev
      - libgbm-dev
      - libgtk-3-dev
      - libibverbs-dev
      - libjemalloc-dev
      - libjpeg8-dev
      - libncurses5-dev
      - libnuma-dev
      - librbd-dev
      - librdmacm-dev
      - libsasl2-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libseccomp-dev
      - libsnappy-dev
      - libspice-protocol-dev
      - libspice-server-dev
      - libusb-1.0-0-dev
      - libusbredirparser-dev
      - libvde-dev
      - libvdeplug-dev
      - libvte-2.91-dev
      - libxen-dev
      - liblzo2-dev
      - libx11-dev
      - libxml2-dev
      - libepoxy-dev
      - libglib2.0-dev
      - libfdt-dev
      - libpixman-1-dev
      - xfslibs-dev
      - zlib1g-dev
      - libnfs-dev
      - libiscsi-dev
      - libpulse-dev
      - ninja-build
      - qt5-qmake
      - intltool
      - libvncserver-dev
      - libssl-dev
      - xutils-dev
      - meson
      - libva-dev
      - libslirp-dev
      - ovmf
      - libgles-dev
      - qtbase5-dev
      - qtdeclarative5-dev
      - libldap2-dev
    stage-packages:
      - libaio1t64
      - libbluetooth3
      - libboost-iostreams1.83.0
      - libboost-random1.83.0
      - libboost-thread1.83.0
      - libbrlapi0.8
      - libepoxy0
      - libflac12t64
      - libiscsi7
      - libjemalloc2
      - libnfs14
      - libnuma1
      - librados2
      - librbd1
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsndio7.0
      - libspice-server1
      - libusb-1.0-0
      - libusbredirparser1t64
      - libvdeplug2t64
      - libxencall1t64
      - libxendevicemodel1t64
      - libxenevtchn1t64
      - libxenforeignmemory1t64
      - libxengnttab1t64
      - libxenmisc4.17t64
      - libxenstore4t64
      - libxentoolcore1t64
      - libxentoollog1t64
      - libyajl2
      - libxi6
      - libxss1
      - libasn1-8t64-heimdal
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libbrotli1
      - libcairo-gobject2
      - libcairo2
      - libcurl3-gnutls
      - libdatrie1
      - libfdt1
      - libfribidi0
      - libgdk-pixbuf2.0-0
      - libgraphite2-3
      - libgssapi3t64-heimdal
      - libgtk-3-0
      - libharfbuzz0b
      - libhcrypto5t64-heimdal
      - libheimbase1t64-heimdal
      - libheimntlm0t64-heimdal
      - libhx509-5t64-heimdal
      - libkrb5-26t64-heimdal
      - libldap2
      - libnghttp2-14
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libroken19t64-heimdal
      - librtmp1
      - libssh-4
      - libthai0
      - libvte-2.91-0
      - libvncclient1
      - libwind0t64-heimdal
      - libdouble-conversion3
      - libevdev2
      - libpcre2-16-0
      - libslirp0
      - qml-module-termwidget
    prime:
      # Remove cruft
      - -usr/share/qemu/qemu-nsis.bmp

  post:
    after: [ pvms ]
    build-snaps: [ mesa-2404, hybris-2404 ]
    build-packages:
      - execstack
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      $CRAFT_PART_SRC/bin/gpu-2404-cleanup mesa-2404
      $CRAFT_PART_SRC/bin/gpu-2404-cleanup hybris-2404
      rm -rf $CRAFT_PRIME/usr/share/{doc,man}
      cd $CRAFT_PRIME/usr
      for f in $(ls share/qemu/openbios-*); do
        execstack -c $f
      done
    prime:
      - bin/gpu-2404-wrapper
